test:btsoot:
  script:
    - python3.6 -m py_compile btsoot.py

test:copy:
  script:
    - cd copy
    - make test
    - cd ..

build:
  stage: build_copy
  script:
    - cd copy
    - make
    - cd ..
  artifacts:
    paths:
      - ./copy/copy
