test:
  stage: test_python
  script:
    - python3.6 -m py_compile btsoot.py
  stage: test_copy
  script:
    - cd copy
    - make test
    - cd ..

build:
  stage: build_copy
  script:
    - cd copy
    - make
    - cd ..
  artifacts:
    paths:
      - ./copy/copy
